### ISSUE TITLE
Enabling this plugin results in "no response" from all HB devices

### ISSUE THREAD

**Issue by shugass** [ebaauw/homebridge-ws#32]
Hello, when I enable this plugin it breaks to connection in Home to all my Homebridge devices (but not the native homekit devices). They range from wemo to nest to Ring. If i disable this plugin and restart homebridge then all devices come back online in Home.
All the accessories work and respond directly in homebridge, however they do not in Home on my iPhone when it is enabled.
It used to work, i think the issue may have started one or two plugin versions ago.
I love the plugin, so hopefully it is something easy?
Thanks so much!

**Comment by ebaauw** [comment]
Can you and re-install Homebridge WS, so it picks up the latest version of homebridge-lib?  If the issue persists, try disabling the other plugins, or run Homebridge WS in a child bridge, to make sure the issue isn’t caused by interference of another plugin.  If the issue still persists, please capture and attach a full debug log, see https://github.com/ebaauw/homebridge-hue/wiki/FAQ#homebridge.

**Comment by Pblondin123** [comment]
fyi i disabled the plugin, then went -1 (enabled), then latest, all good since.

**Comment by ebaauw** [comment]
I think it's the same cause as #31: incorrect handling of negative temperatures.

**Comment by shugass** [comment]
Uninstalled -> reinstalled. Works great again, thanks!!!!
