### ISSUE TITLE
Mysterious value while setting automation through Home+5 app

### ISSUE THREAD

**Issue by FranciRoosters** [ebaauw/homebridge-ws#42]
Hello, I’ve been trying to set up an automation using the condition value in the Home+5 app. When I select it, I see a number value, precisely 60.12891. I’ve no idea what this means and what number I should input whenever it’s cloudy or rainy. Thank you for your support.

**Comment by ebaauw** [comment]
Not sure what you mean, could you please attach a screenshot?

Afaik, HomeKit only supports automations on numeric values, so you shouldn't even be able to select _Condition_.  I doubt that Apple would silently have changed that in iOS 15?  That's why I expose the raw value under _Condition Category_, see #15.  However, this is an integer value, not a floating point.  How long have you been using Homebridge WS.  Maybe you're hit by #28?
