### ISSUE TITLE
[Feature request] Rename possibility of the accesory

### ISSUE THREAD

**Issue by sanderrobbers** [ebaauw/homebridge-ws#44]
Now the accesory are in the english language stated in the code itself

```
this.wsServices.temperature.characteristicDelegate('temperature'),
this.wsServices.humidity.characteristicDelegate('humidity'),
this.wsServices.pressure.characteristicDelegate('pressure')
```
It will be nice to have a rename possibility

**Comment by toets23** [comment]
Now the accesory are in the english language stated in the code itself

```
this.wsServices.temperature.characteristicDelegate('temperature'),
this.wsServices.humidity.characteristicDelegate('humidity'),
this.wsServices.pressure.characteristicDelegate('pressure')
```
It will be nice to have a rename possibility

**Comment by ebaauw** [comment]
I don't understand what you're asking.  Accessory names can be changed from HomeKit.  The code you're showing concerns internal variable names, that are not visible to the HomeKit user and appear only in the debug log messages.  I'm not going to support localisation of log messages.

Note that the HomeKit accessory protocol doesn't support localisation, as this is (should be) handled by the HomeKit application.  E.g. the _Current Temperature_ characteristic always reports the temperature in °C; it's up to the HomeKit app to convert that to °F, when desired by the user.  Similarly, characteristic types are identified by UUID, it's up to the HomeKit app to translate that Into a (local language) name.  That's why you actually see different HomeKit apps using different names for the same characteristic type: e.g. _On_ vs _Power_.

**Comment by sanderrobbers** [comment]
Oh, i get it, so I will rename to my own localization within homebridge "Accessoires". And also rename it to the same in the Homekit application.

Currently I am seeing:

_Location_ Humidity
_Location_ Temperature
_Location_ Weather

**Comment by ebaauw** [comment]
These are the service names.  You can update them from any HomeKit app, and they sync to all your devices and apps.  The Homebridge UI is not a proper HomeKit app, but I think you should be able to rename the tiles  there as well.  Not sure, as I don’t use the _Accessories_ feature of the UI.
