### ISSUE TITLE
Can't use wind speed as a comparative condition in Eve

### ISSUE THREAD

**Issue by guillochon** [ebaauw/homebridge-ws#46]
Not sure if there's anything that can be done on the plugin side of things, but figured I'd ask: In Eve, I can use temperature `<=` or temperature `>=` X as a "condition" to an automation running. This is not available for the wind speed exposed by this plugin, I can only use the `=` condition (which is not terribly useful for a floating point number). The only difference I can see in the plugin config is that a unit is defined for the temperatures exposed whereas there isn't one defined for wind speed. Maybe defining the unit is necessary to enable the `>=`/`<=` conditions?

**Comment by guillochon** [comment]
Sorry for the bother, I am closing this as it appears this is a limitation of the "trigger" feature in Eve for any sensor reading.

**Comment by ebaauw** [comment]
Afaik, HomeKit (!) supports triggers and conditions on any numeric or boolean characteristic.  Of course, Apple's Home app only supports a small subset of these, and even Eve doesn't support everything.  I had to use Home+ to create automations on _Target Temperature_ (to sync my smart radiator valves with my central heating thermostat).

HomeKit doesn't support automation triggers or conditions on text characteristics.  That's why I expose _Condition Category_, in addition to _Condition_.

Double-checked in Home+, I can create a trigger _Wind Speed_ greater or equal to 6.2 m/s, and Eve even displays it as >=, but when editing it, Eve changes it to =.
